app:
  title: "🌍 Traducteur automatique des langues gabonaises"
  description: "Application de traduction automatique basée sur un modèle NLLB fine-tuné pour des langues africaines du Gabon, notamment le Fang, le Punu et le Myènè."

model:
  # "local" : charge le modèle et le tokenizer depuis un dossier local.
  # "huggingface" : charge le modèle et le tokenizer depuis Hugging Face Hub.
  source: "huggingface"

  # Dépôt Hugging Face contenant le modèle fine-tuné.
  path_or_repo: "Minloubd/nllb-fang-fr-v5-600M-adafactor"

  # Quantification dynamique INT8 pour réduire l'utilisation mémoire sur CPU.
  quantize_int8: true

  # False car le modèle est téléchargé depuis Hugging Face Hub.
  local_files_only: false

  trust_remote_code: false

generation:
  max_input_length: 512
  max_new_tokens: 256
  num_beams: 4
  length_penalty: 1.0
  repetition_penalty: 1.0
  early_stopping: true

# Langues prises en charge.
#
# IMPORTANT :
# Les identifiants doivent correspondre exactement aux tokens
# utilisés par le tokenizer pendant le fine-tuning.
#
# Exemple NLLB standard :
#   Français -> fra_Latn
#
# Fang est ici associé au token personnalisé utilisé lors du fine-tuning.
# Remplacer les valeurs Punu et Myènè par les tokens exacts
# utilisés dans leurs modèles/tokenizers respectifs.

languages:
  Français: "fra_Latn"
  Fang: "fang_Latn"
  Punu: "puu_Latn"
  Myènè: "mye_Latn"